package com.example.eduspace.notification.enums;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_MOVED_TO_CHAT,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN,
    NEW_MESSAGE,
    CONTACT_SHARED,
    NEW_FOLLOWER,
    POST_LIKED,
    POST_COMMENTED,
    POST_MENTION,
    COMMENT_MENTION
}