# application-local.yml
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

eduspace:
  jwt:
    secret-key: ${JWT_SECRET}
    access-token-expiration: 900000
    refresh-token-expiration: 2592000000
    password-reset-token-expiration: 300000

  app:
    frontend-url: ${FRONTEND_URL}
    backend-url: ${BACKEND_URL}

  google:
    client-id: ${GOOGLE_CLIENT_ID}

  storage:
    url: ${SUPABASE_URL}
    service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}
    bucket: ${SUPABASE_BUCKET:eduspace-uploads}
    max-file-size-mb: 10

logging:
  level:
    root: INFO
    com.sanket.eduspace: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
